### ISSUE TITLE
Must Mark as Saved_Refresh_Mark as Saved Again to Keep Last Tested Date

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#1]
When marking a test as pass, I get a message at the top that says Error - Unknown error. The test case does get marked as passed and only temporarily gets a Last Tested Date of today's date.  Upon refreshing the browser and navigating back to the test case, it still says passed, but says Never Tested.  If you select Pass again (even though it already says pass), then it updates the last tested to today's date.  Refreshing the browser and returning to the test shows that the date has now been maintained.  

**Repro Steps:**
1. Open a test and perform test action steps
2. Close Test
3. Click on dropdown for test case
4. Select Pass
5. Notice Error - Unknown Error in red at the top
6. Notice that the Last Tested Date has changed from Never Tested to today's date
7. Refresh the browser
8. Navigate back to the Module and Test Case
9. Notice that the date label now says Never Tested
10. Even though the test is marked as Pass, select Pass again
11. Notice that Last Tested date is marked as today's date again
12. Refresh the browser
13. Navigate back to the Module and Test Case
14. Notice that the last tested date has been maintained

**Expected behavior**
- No error should be displayed
- Today's date should persist for the Last Tested Date upon first selection of Pass or Fail, etc of the test case

[Must Mark as Saved_Refresh_Mark as Saved Again to Keep Last Tested Date.zip](https://github.com/ToucanTesting/ToucanTesting/files/1993004/Must.Mark.as.Saved_Refresh_Mark.as.Saved.Again.to.Keep.Last.Tested.Date.zip)

**Comment by lgranneman** [comment]
I have found that this is not only if you OPEN the test case, but also if you VIEW the test case.

**Comment by dapperdandev** [comment]
@lgranneman Thanks for the repro steps. I couldn't repro it on my own yesterday.

**Comment by djbreen7** [comment]
@lgranneman: More discovery today. I wasn't able to repro it previously because it seems to only affect test cases that have child entities (expected results, pre-conditions, and test actions).

I'm feeling good about a solution I think I've found. It should fix https://github.com/ToucanTesting/ToucanTesting/issues/5 as well.

**Comment by djbreen7** [comment]
@lgranneman: The fixes are deployed. Please attempt to repro this and https://github.com/ToucanTesting/ToucanTesting/issues/5 when you have some time.

**Comment by lgranneman** [comment]
@djbreen7 

That's awesome!  I will test in the morning.  If it all seems to be working well, I'd love to attempt this sprint in Toucan.   I will let you know how it goes.

**Comment by djbreen7** [comment]
@lgranneman : Cool beans. I would go in there with the intention of breaking it. Don't start anything that you want to persist. I'll still need to re-import things
