### ISSUE TITLE
Deleted Test Cases are Included in Newly Created Run

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#11]
**Describe the bug**
After deleting test cases from a suite, then creating a new run, the new run includes the deleted test cases.

**To Reproduce**
1. Open a module in suites
2. Delete a test case
3. Refresh the page
4. Verify the test case is no longer present
5. Navigate to Runs 
6. Add a new run
7. Open the module from which the test case was deleted
8. Notice that the deleted test case is included in the run

**Expected behavior**
Deleted test cases should not be included in a new run.

[Toucan - Deleted Test Cases are Included in New Run.zip](https://github.com/ToucanTesting/ToucanTesting/files/2010053/Toucan.-.Deleted.Test.Cases.are.Included.in.New.Run.zip)

**Comment by djbreen7** [comment]
Fixed with 
https://github.com/ToucanTesting/ToucanTesting.Api/commit/3d3e899e9eb343e29ed191f8bf76b3c82cd3ccba
