### ISSUE TITLE
NTH - Allows for Duplicate Test Case Names

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#13]
Currently you are able to create test cases with the exact same name

**Describe the solution you'd like**
A warning should appear and not allow for duplicate test case names

![toucan - allows for duplicate test case names](https://user-images.githubusercontent.com/39166908/40133072-3882fb20-5904-11e8-8953-f84f01bb3da1.png)

**Comment by djbreen7** [comment]
Fixed in [v0.0.3](https://github.com/ToucanTesting/ToucanTesting.Client/releases/tag/v0.0.3)
