### ISSUE TITLE
NTH - Add Additional Sorts by Test Case Number and Alphabetically

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#14]
It would be great to have a sort by test case number since many test cases were created in a logical kind of order.  Also, this would help when adding, duplicating or move test cases where they are added every two lines above the bottom of the list. 

In addition, sorting alphabetically by test case name would allow us the ability to be sure we are not duplicating a test case which may be named similarly or the same.

![add sorts - by test case number_alphabetically](https://user-images.githubusercontent.com/39166908/40134834-32b82b8e-5909-11e8-9fb3-708d5390b8f5.png)

**Comment by djbreen7** [comment]
https://github.com/ToucanTesting/ToucanTesting.Client/commit/791433873e973e4ddbedc00aa8df00a8e5516a9b
