### ISSUE TITLE
NTH - Add Search Capability to Module

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#15]
It would help to have a search option for finding a test case to verify that it exists so duplicates are not created.  

It would be best if it could search on an exact match, a partial begins with and a contains search.  

![add search capability to modules](https://user-images.githubusercontent.com/39166908/40135120-13e01428-590a-11e8-8780-d5ee5776cab7.png)

**Comment by djbreen7** [comment]
@lgranneman: Next on my list! :)

Once I came back to kno2 and tried really doing a test run, I realized how nice this would be.

**Comment by lgranneman** [comment]
@djbreen7 

Totally agree!

**Comment by dapperdandev** [comment]
Done and Deployed

**Comment by lgranneman** [comment]
@djbreen7 

Love this feature!!! Thanks
