### ISSUE TITLE
Creating a Run Orders Test Cases Differently Than in the Suite

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#16]
**Describe the bug**
When you create a run, the test cases are sometimes ordered differently than in the suite, but it seems that the runs match if you create more than one run.  I'm not sure what the order really is, but it is definitely mixed up sometimes.  

I don't think there is any harm necessarily in this, but I lose a little confidence in all test cases being included when I see something like this if you create the run and then check before any cases are removed or added to the suite.  

**To Reproduce**
1. Look at the Release module in Suites
2. Create a new run
3. Notice the different order (easiest to compare the test case numbers)

![toucan - runs are not created with all test cases in the same order as the suites](https://user-images.githubusercontent.com/39166908/40140043-72e85c34-5917-11e8-8989-496f94643554.png)

**Comment by djbreen7** [comment]
@lgranneman: Incoming fix will initially sort by ID. This may be a Work In Progress

**Comment by djbreen7** [comment]
Fixed with https://github.com/ToucanTesting/ToucanTesting.Client/pull/5/commits/b9bbe1c5ecdc4da9f4ffbde68d6db03224713874
