### ISSUE TITLE
Report Pulls Total Number of Test Cases from Suite, Not Run

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#19]
**Describe the bug**
When viewing the report for a Run, I noticed that one the modules was marked as two tests passed and 1 not tested.  I went into the module and there were only 2 cases in that module.  I then went to the Suite and found that same module.  I had added a new test case since the creation of the run.  So, it appears that it is looking at all the existing test cases for a suite when reporting on what has or has not been completed in a run.  

**To Reproduce**
1. Create a Run
2. View the Report
3. Hover over a module and make note of how many test cases are listed as DNT for that module
4. Navigate to Suites > Kno2fy
5. Create a new test case in that same module
6. Navigate back to Run
7. View the Report
8. Hover over the same module
9. Notice that DNT has changed and now has 1 additional test case

**Expected behavior**
Test cases that are created after the creation of a Run should not be counted in DNT for a module since they cannot be tested in that Run. 

[Toucan - Test Case Added After Run Creation is Inlcuded in DNT.zip](https://github.com/ToucanTesting/ToucanTesting/files/2040338/Toucan.-.Test.Case.Added.After.Run.Creation.is.Inlcuded.in.DNT.zip)

**Comment by djbreen7** [comment]
Thanks Linda. I repro'd locally. Should have a fix in tonight.

**Comment by djbreen7** [comment]
@lgranneman: Think I actually was able to fix it already. Feel free to verify.

**Comment by lgranneman** [comment]
@djbreen7 

Yes, I have verified this is definitely resolved!
