### ISSUE TITLE
Duplicating a Test Case Reorders Test Actions

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#20]
If you add steps and reorder test action steps, then duplicate the test case, the test actions are reordered in a completely different order.  This really becomes a mess when there are many steps in the test case.

**Repro**
Open a Test Case
Add a couple steps to the Test Actions
Reorder those steps
Reorder some existing steps
Close out of Test Case
Duplicate Test Case
Notice the Test Actions are in a different order

![toucan - duplicate a reordered test case reorders test actions in copy](https://user-images.githubusercontent.com/39166908/40816217-3e7ade94-6511-11e8-9c35-00c79cbf8a60.png)

**Comment by djbreen7** [comment]
@lgranneman: Deploying a fix now. It may have side effects.

The Test Actions were never actually being sorted by a hidden property named "sequence". It seemed to only affect when being duplicated though.

I've implemented the fix, but this might affect any previous test cases where steps were re-ordered.
