### ISSUE TITLE
Sort on Description Appears to be Case Sensitive

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#22]
**Describe the bug**
If you sort on description - ascending, it appears that it is case sensitive.  Those with an asterisk appear first, then those beginning with capital A, then those with lower case letters after the entire alphabet beginning with a Capital letter. 

**Expectation**
Ignore upper/lower case and sort alphabetically on letter 

[Toucan - Sort on Description Appears to be Case Sensitive.zip](https://github.com/ToucanTesting/ToucanTesting/files/2104141/Toucan.-.Sort.on.Description.Appears.to.be.Case.Sensitive.zip)

**Comment by djbreen7** [comment]
Fixed in v0.0.2
