### ISSUE TITLE
Drag and Drop - Lose Steps in Tab and Test Actions - Can't Readd Anything

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#23]
**Describe the bug**
If you drag and drop a precondition for example, it creates a blank line above the top row. Then if you try to move it back, it creates a duplicate line (I didn't get that on video).  If you delete the duplicate, then try to move anything, you can't move anything.  Navigate to Test Actions you now notice that they are missing.  If you attempt to add a precondition or a test action step, it won't let you add anything.  If you close out and reopen the test case, the preconditions are gone and the test actions are still missing.  You cannot add anything in the test case. 

I'm not sure if you can fix this so I can add steps back in or if I have to delete the test case and add a new one.  I did this on a couple different test cases.

[Toucan - Drag and Drop_Lose Test Case Details_Can't Add Details Back In.zip](https://github.com/ToucanTesting/ToucanTesting/files/2123978/Toucan.-.Drag.and.Drop_Lose.Test.Case.Details_Can.t.Add.Details.Back.In.zip)
[Toucan - After Close and Reopen - Expected Results and Test Actions all gone_Cannot Add.zip](https://github.com/ToucanTesting/ToucanTesting/files/2123980/Toucan.-.After.Close.and.Reopen.-.Expected.Results.and.Test.Actions.all.gone_Cannot.Add.zip)

**Comment by djbreen7** [comment]
Fixed.
