### ISSUE TITLE
Ability to Edit/Delete an Issue From a Run

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#24]
When retesting an issue which had a failure and a JIRA issue logged, I find myself going through the retesting in the Run and then trying to remove the logged JIRA issue from that particular issue, but I can't.  The only way now is to go to Issues or back to Suites to remove a JIRA issue that is now resolved.  

This is a nice to have when you have time.

**Comment by djbreen7** [comment]
I'm not sure I follow. Are you saying that clicking the trash can to the side of the test issue within the test case isn't working?

![image](https://user-images.githubusercontent.com/13296622/42457973-18b4c8c4-8356-11e8-97b7-152c7033e456.png)

**Comment by lgranneman** [comment]
@djbreen7 

OMG - Don't know how I missed that trash can.  Close this issue.  Sorry.

**Comment by lgranneman** [comment]
@djbreen7 

I take that back.  I have one that I logged and the trash can does not delete.  It just says error.

**Comment by lgranneman** [comment]
@djbreen7 

So sorry - I refreshed my browser and tried again, and it allowed me to delete it.  It's Monday!!!

**Comment by djbreen7** [comment]
@lgranneman: Okay. I'll leave it open for another week. Sounds like it might be a little flaky. Let me know if you have a similar problem later.

**Comment by lgranneman** [comment]
@djbreen7 

Will do - Thanks!
