### ISSUE TITLE
Highlight Text and Replace Text or Delete

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#25]
**Describe the bug**
If I need to edit either Expected Results, Preconditions, or Test Actions, I cannot highlight any text and replace or delete it.  The only ways are to just click in the field and delete the unwanted text or use the shift key and the arrow keys.  

If you edit a test case name, you have this ability.  I find myself trying to do this within a text case all the time and I am pretty sure it used to work. 

**To Reproduce**
1. Steps to reproduce the behavior:
2. Open a test case
3. Click any tab
4. Click in any line listed for that tab
5. Try to highlight by dragging mouse or clicking/holding shift/and clicking
6. Notice that you cannot highlight to replace or delete text

**Expected behavior**
The expected behavior would be to highlight just like you can when editing a test case name.

[Toucan - Cannot Highlight to Edit or Replace Text.zip](https://github.com/ToucanTesting/ToucanTesting/files/2156952/Toucan.-.Cannot.Highlight.to.Edit.or.Replace.Text.zip)

**Comment by djbreen7** [comment]
Thanks Linda. As a temporary workaround, you can perform the following action:

1. Click the item that you want to edit so that it become editable.
2. Triple-click to highlight all of the text.

![triple](https://user-images.githubusercontent.com/13296622/42192716-cd5f8c70-7e27-11e8-82df-8c5316484be6.gif)

**Comment by djbreen7** [comment]
@lgranneman Should have a fix in for this later today.

![highlight](https://user-images.githubusercontent.com/13296622/43471072-576fc282-94a7-11e8-8ec0-f148e8f83144.gif)
