### ISSUE TITLE
Report for Sprint 109 Integration Will Not Load

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#26]
**Describe the bug**
When selecting to view the report for _Sprint 109 Integration_, it just circles, but never loads.  I can view reports for every other run - just not the current one.  

In the dev console, I get an error - Cannot set property "testResult" of undefined.

If I create a new run and mark some tests passed, then attempt to view the report, I have no issue.  Not sure why just this one report will not load.

**To Reproduce**
Log in to Toucan
Navigate to Runs
For Sprint 109 Integration, click view report
Notice that the report never loads

[Toucan - Cannot View Report for Sprint 109 Integration.zip](https://github.com/ToucanTesting/ToucanTesting/files/2159821/Toucan.-.Cannot.View.Report.for.Sprint.109.Integration.zip)

![toucan - cannot view report - testresults undefined](https://user-images.githubusercontent.com/39166908/42226663-245a0fdc-7ea5-11e8-9e8e-ecf389baea41.png)

**Comment by djbreen7** [comment]
Weird. I didn't update anything last night. I'll be able to troubleshoot here in a few.

**Comment by lgranneman** [comment]
@djbreen7 

I updated a lot of details for test cases yesterday and moved some to different modules.  I could view it earlier in the day, but around 5:00 yesterday when I tried before the end of my day, it quit working.

**Comment by djbreen7** [comment]
Okay. I've found the issue. 

Both the TestResult and the TestCase have a ModuleId reference. If a TestRun is started and cases are tested, then moved to another module, the TestResult will still reference the old module.

I've gone back and fixed the broken references, but I haven't fixed the code itself. You can see the test run now, but it will break again if any cases are moved to different modules.

I'll see if I can find time today to make a permanent fix. :)

**Comment by djbreen7** [comment]
@lgranneman ☝️

**Comment by lgranneman** [comment]
@djbreen7 

Ah, that makes sense.  If I move them first, then test them, will that work okay? If not, I can update the cases and move them to the modules later - I'll just keep notes. 

I'm working on the Kno2 Fax cases and actually that module should end up going away completely.  That module was created from a Smartsheet list of anything involving a fax number.  We have Document Sources - Fax Numbers, plus some go on users, releases, etc.

**Comment by djbreen7** [comment]
Right. If you move them first, then test them, it should work okay.

**Comment by djbreen7** [comment]
Fixed in v0.0.2
