### ISSUE TITLE
Pagination on Test Runs - Last Does Not Respond

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#29]
**Describe the bug**
I had 11 test runs created, so two pages.  I tested each button, but the Last button does not respond. 

**To Reproduce**
Click Next to go to page 2
Click Previous and it takes you to page 1
Click Next to go to page 2
Click First to go to the first page (1)
Click Last to go to the last page (2), but notice that it does not respond

**Expected behavior**
Clicking last should take you to the last page of runs, which in this case would be page 2

[Toucan - Pagination on Test Runs_Last Does Not Respond.zip](https://github.com/ToucanTesting/ToucanTesting/files/2185608/Toucan.-.Pagination.on.Test.Runs_Last.Does.Not.Respond.zip)

**Comment by djbreen7** [comment]
Fixed in [v0.0.3](https://github.com/ToucanTesting/ToucanTesting.Client/releases/tag/v0.0.3)
