### ISSUE TITLE
Cannot View Report for Sprint 105 Integration_2

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#3]
I've attempted several times to view the report for this current run, but it just spins and never produces a report.  An error is displayed in the dev console.

ERROR TypeError:  Cannot set property 'testResult' of undefined

![toucan - view report for sprint 105 integration_2](https://user-images.githubusercontent.com/39166908/39900844-41ea1474-548a-11e8-8fc8-7ef540f7beef.png)

**Comment by dapperdandev** [comment]
@lgranneman: I saw this yesterday too. Looking into

**Comment by djbreen7** [comment]
@lgranneman I have a fix ready for this. Will deploy ASAP.

**Comment by djbreen7** [comment]
Deployed this fix. We'll keep an eye on it. For a minute.
