### ISSUE TITLE
Need Filter for Not Automated

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#31]
I often sort by priority in descending order, but mixed in with that will be automated test cases, which I don't need to test.  Is there a way that a filter could be added to show non-automated test cases and then I could still use the priority feature? This way I wouldn't test an automated case by mistake.

[Toucan - Need Filter for Not Automated.zip](https://github.com/ToucanTesting/ToucanTesting/files/2193562/Toucan.-.Need.Filter.for.Not.Automated.zip)

**Comment by djbreen7** [comment]
Added 'Manual' Filter
