### ISSUE TITLE
Resulted Message Status Does Not Persist When Searching in a Run

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#32]
**Describe the bug**
If I have resulted test cases as passed in a run, but then search in that run for those messages, they no longer have the pass status.  Instead they are pending.  

The expectation would be that the status would be maintained if you are searching within a run.  So if the status were fail or pass, etc, that is the status that would appear if you have searched for test cases in a run.

**To Reproduce**
Example:
1. Under notifications, search for failed
2. Complete testing for the four test cases
3. Scroll to the top of the run
4. In the search field, type failed
5. Click Enter
6. Notice that the four test cases just resulted all have a pending status

[Toucan - Resulted Message Status Does Not Persist When Searching in a Run.zip](https://github.com/ToucanTesting/ToucanTesting/files/2247363/Toucan.-.Resulted.Message.Status.Does.Not.Persist.When.Searching.in.a.Run.zip)

**Comment by djbreen7** [comment]
@lgranneman Should be fixed now. Might have to force refresh/clear cache.

It takes a second to display the result.

![results](https://user-images.githubusercontent.com/13296622/43533629-7fe6fc50-9572-11e8-89c0-ec155bc6fecc.gif)

**Comment by lgranneman** [comment]
Awesome!  Didn't even have to clear my cache!
