### ISSUE TITLE
Failed Messages in Run Report Does Not Show Red Bugs

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#33]
**Describe the bug**
If you View Report for a run that has issues logged and you click on the Failed tab of the report, the issues are listed, but the bugs are gray.  They should be red, indicating that an issue has been logged. 

In the attached image, all of the failed test cases listed have issues logged. 

![toucan - issues for run are not displaying red bugs](https://user-images.githubusercontent.com/39166908/43615439-434f83fa-967d-11e8-9870-a33e5fc4dbea.png)

**Comment by djbreen7** [comment]
Thanks @lgranneman. Fixing now.

Part of this fix will include viewing the Test Case modal when clicking on it's name. That was broken for the same reason.

**Comment by djbreen7** [comment]
![image](https://user-images.githubusercontent.com/13296622/43647289-6e933b8e-96f4-11e8-892f-7f3d98ccc213.png)
