### ISSUE TITLE
Time Stamp Not Using Local Time?

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#7]
**Describe the bug**
As I am going through and updating the Google Workbook, I am noticing manual test cases I had run and documented in the workbook are all 1 day before the date listed as the last updated date in the test run.  Is it possible it is not using local time?

**Comment by lgranneman** [comment]
@djbreen7 

I didn't know if it would be a big issue or not.  Honestly, I don't think it matters a whole lot given our use of that data in just making sure things are tested frequently enough.   Let's just close this one.

**Comment by djbreen7** [comment]
Potentially fixed with:
https://github.com/ToucanTesting/ToucanTesting.Client/pull/5/commits/95ee90213cba5486f1cffa90c79a08007f4c1494
