### ISSUE TITLE
NTH - Adding or Duplicating a Test Case Should Add it to the Bottom of Test Cases for a Module

### ISSUE THREAD

**Issue by lgranneman** [ToucanTesting/ToucanTesting#9]
When adding a new test case, duplicating a test case or moving a test case to another module, it is added as the second to the last case in the list of cases.  As each new test case gets added, the new ones all bump up two spots.  When you add or duplicate a test case, you have to go in and add or edit it, so this makes it difficult to locate your test case, especially if you have added more than one.  When you do the reverse and delete one of those test cases, the newer test cases all move down two spots as well.  

**Describe the solution you'd like**
Newly added, duplicated or moved test cases should be added to the bottom of the list of test cases in a module.

**Describe alternatives you've considered**
An alternative may be to add a sort by the test case number.

[Toucan - Adding or Duplicating a Test Case Should Add it to the Bottom of the List.zip](https://github.com/ToucanTesting/ToucanTesting/files/2009939/Toucan.-.Adding.or.Duplicating.a.Test.Case.Should.Add.it.to.the.Bottom.of.the.List.zip)

**Comment by djbreen7** [comment]
Fixed in [v0.0.3](https://github.com/ToucanTesting/ToucanTesting.Client/releases/tag/v0.0.3)
